esphome:
  name: bedroom

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: True

sensor:
  - platform: scd4x
    co2:
      name: "Bedroom CO2"
      filters:
        - median
    temperature:
      name: "Bedroom Temperature"
      filters:
        - median
    humidity:
      name: "Bedroom Humidity"
      filters:
        - median

switch:
  - platform: restart
    name: "Bedroom Restart"
logger:

api:

ota:
  platform: esphome
