esphome:
  name: office
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: True

sensor:
  - platform: scd4x
    co2:
      name: "Bedroom CO2"
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"

switch:
  - platform: restart
    name: "Bedroom Restart"
logger:

api:

ota:
