substitutions:
  devicename: "gas-meter"
  friendly_name: "Gas meter"

esphome:
  name: $devicename
  comment: $friendly_name
  build_path: .builds/$devicename

esp32:
  board: featheresp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

web_server:
  port: 80

ota:
  platform: esphome

sensor:
  - platform: homeassistant
    entity_id: sensor.duju_skaitliukas
    id: gas_meter
    name: gas_meter

  - platform: qmc5883l
    address: 0x0D
    field_strength_x:
      name: "Gas Meter Field Strength X"
    field_strength_y:
      name: "Gas Meter Field Strength Y"
    field_strength_z:
      name: "Gas Meter Field Strength Z"
    temperature:
      name: "Gas Meter Temperature"
      filters:
        - offset: 34.0
    range: 200uT
    oversampling: 512x
    update_interval: 1s

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

font:
  - id: s
    file: "fonts/BebasNeue-Regular.ttf"
    size: 19
  - id: m
    file: "fonts/BebasNeue-Regular.ttf"
    size: 28
  - id: l
    file: "fonts/BebasNeue-Regular.ttf"
    size: 58

display:
  - id: my_display
    platform: st7789v
    model: TTGO TDisplay 135x240
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 270°
    update_interval: 5s
    lambda: |-
      it.printf(it.get_width(), 0, id(l), TextAlign::TOP_RIGHT, "%08.2f", id(gas_meter).state);
