esphome:
  name: lightkeeper
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: git
      url: https://github.com/Ulrar/esphome-temp.git
      ref: ble_write_action
    components: [ ble_client ]

web_server:
  port: 80

esp32_ble_tracker:

ble_client:
  - mac_address: D3:19:0A:0F:06:B6
    id: basestation_1_client
  - mac_address: D4:FE:BD:32:15:67
    id: basestation_2_client

sensor:
  - &lhb_sensor
      platform: ble_client
      ble_client_id: basestation_1_client
      id: basestation_1
      service_uuid: '00001523-1212-efde-1523-785feabcd124'
      characteristic_uuid: '00001525-1212-EFDE-1523-785FEABCD124'
      icon: 'mdi:virtual-reality'
      notify: true
  - <<: *lhb_sensor
    ble_client_id: basestation_2_client
    id: basestation_2

switch:
  - &lhb_switch
    platform: template
    name: "Base station 1"
    lambda: return id(basestation_1).state == 0x0b;
    turn_on_action:
      - ble_client.ble_write: &on_action
          id: basestation_1_client
          service_uuid: 00001523-1212-efde-1523-785feabcd124
          characteristic_uuid: 00001525-1212-EFDE-1523-785FEABCD124
          value: [0x01]
    turn_off_action:
      - ble_client.ble_write: &off_action
          id: basestation_1_client
          service_uuid: 00001523-1212-efde-1523-785feabcd124
          characteristic_uuid: 00001525-1212-EFDE-1523-785FEABCD124
          value: [0x00]
  - <<: *lhb_switch
    name: "Base station 2"
    lambda: return id(basestation_2).state == 0x0b;
    turn_on_action:
      - ble_client.ble_write:
          <<: *on_action
          id: basestation_2_client
    turn_off_action:
      - ble_client.ble_write:
          <<: *off_action
          id: basestation_2_client
  - platform: restart
    name: "Lightkeeper Restart"

logger:

api:

ota:
