esphome:
  name: living-room
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

uart:
  rx_pin: GPIO23
  tx_pin: GPIO22
  baud_rate: 9600

i2c:
  sda: GPIO33
  scl: GPIO32
  scan: True

sensor:
  - platform: mhz19
    id: living_room_mhz19
    co2:
      name: "Living Room CO2"
    temperature:
      name: "Living Room Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false
  - platform: bme280
    temperature:
      name: "Living Room Temperature 2"
    pressure:
      name: "Living Room Pressure"
    humidity:
      name: "Living Room Humidity"
    address: 0x76
    update_interval: 60s

switch:
  - platform: restart
    name: "Living Room Restart"
  - platform: template
    name: "Living Room CO2 Baseline Calibration"
    assumed_state: true
    turn_on_action:
      - mhz19.calibrate_zero: living_room_mhz19

logger:

api:

ota:
