esphome:
  name: office
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

uart:
  rx_pin: GPIO17
  tx_pin: GPIO16
  baud_rate: 9600

i2c:
  sda: GPIO32
  scl: GPIO33
  scan: True

sensor:
  - platform: mhz19
    id: office_mhz19
    co2:
      name: "Office CO2"
    temperature:
      name: "Office Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false
  - platform: bmp280
    temperature:
      name: "Office Temperature 2"
    pressure:
      name: "Office Pressure"
    address: 0x76
    update_interval: 60s
  - platform: scd4x
    co2:
      name: "Office CO2 (SCD40)"
    temperature:
      name: "Office Temperature (SCD40)"
    humidity:
      name: "Office Humidity (SCD40)"

switch:
  - platform: restart
    name: "Office Restart"
  - platform: template
    name: "Office CO2 Baseline Calibration"
    assumed_state: true
    turn_on_action:
      - mhz19.calibrate_zero: office_mhz19

logger:

api:

ota:
