substitutions:
  disp_name: Slingshot

esphome:
  name: slingshot_air_quality
  platformio_options:
    build_unflags: -Werror=all
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

spi:
  id: qspi_bus
  type: quad
  clk_pin: GPIO47
  data_pins:
    - GPIO18
    - GPIO7
    - GPIO48
    - GPIO5

i2c:
  sda: GPIO14
  scl: GPIO13
  scan: True

color:
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%
  - id: my_red
    hex: fc0000
  - id: my_green
    hex: 00fc4c
  - id: my_yellow
    hex: e0e637
  - id: my_orange
    hex: ff7728
  - id: my_white
    hex: ffffff

font:
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font1
    size: 144
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font2
    size: 45

graph:
  - id: my_graph
    duration: 2h
    x_grid: 15min
    y_grid: 50.0
    max_value: 400
    min_value: 50
    width: 500
    height: 200
    traces:
      - sensor: my_wifi_signal
        line_type: SOLID
        continuous: true
        line_thickness: 3
        color: my_green

display:
  - platform: qspi_dbi
    id: my_display
    model: RM67162
    dimensions:
      height: 240
      width: 536
      offset_height: 0
      offset_width: 0
    transform:
      mirror_x: true
      mirror_y: false
      swap_xy: true
    color_order: rgb
    brightness: 150
    cs_pin: 6
    reset_pin: 17
    enable_pin: 38
    pages:
      - id: page1
        lambda: |-
          it.filled_rectangle(0, 0, 536, 240, my_black);
          it.printf(268, 100, id(font1), id(my_yellow), TextAlign::CENTER, "%.0f", 123);
      - id: page2
        lambda: |-
          it.graph(10, 20, id(my_graph), my_yellow);

psram:
  mode: octal

sensor:
  - platform: wifi_signal
    id: my_wifi_signal
    name: ${disp_name} WiFi Status
    update_interval: 10s

  - platform: scd4x
    co2:
      name: "${disp_name} CO2"
    temperature:
      name: "${disp_name} Temperature"
    humidity:
      name: "${disp_name} Humidity"

interval:
  - interval: 10s
    then:
      - display.page.show_next: my_display
      - component.update: my_display

logger:

api:

ota:
  platform: esphome
